"""likes_created

Revision ID: 02ce6dabc4f6
Revises: 5efe586cbefe
Create Date: 2020-08-22 16:03:23.751432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ce6dabc4f6'
down_revision = '5efe586cbefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post_likes', sa.Column('created', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_post_likes', 'created')
    # ### end Alembic commands ###
